### ISSUE TITLE
RuneScape cannot be found in GNOME Software

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/com.jagex.RuneScape#1]
Same issue as https://github.com/flathub/com.albiononline.AlbionOnline/issues/3.

**Comment by AsciiWolf** [comment]
I think you could probably use [this icon](https://github.com/coringao/runescape/blob/master/src/runescape.png).

**Comment by AsciiWolf** [comment]
@Limero Any chance you could use this icon?

**Comment by Limero** [comment]
Is this enough for it to show up in GNOME Software?

**Comment by AsciiWolf** [comment]
I can confirm that RuneScape is now showing up in GNOME Software. Thanks!
