### ISSUE TITLE
2.2.7 is out, please update

### ISSUE THREAD

**Issue by fusion809** [flathub/com.jagex.RuneScape#115]
Hi,

I have been trying to update my Flatpak installation of RS Launcher to the latest available, but I am getting a download error, namely `Error: While downloading https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.6_amd64.deb: Server returned status 404: Not Found`. I checked the URL and found it 404'd in my browser, but https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.7_amd64.deb did not, therefore version 2.2.7 of the RuneScape launcher is out now. 

Thanks for your time,
Brenton

**Comment by Garbee** [comment]
Done with #116. Not sure why the PRs didn't auto-merge after an hour like some previous ones. Perhaps due to the release version update.

🤞 that the launcher binary is actually in this build.
