### ISSUE TITLE
error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by annadane** [flathub/com.jagex.RuneScape#124]
annadane@debian:~$ flatpak run com.jagex.RuneScape
/home/annadane/Jagex/launcher/rs2client: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by MarcWoodyard** [comment]
Same here, but it was working a couple of days ago through.

```sh
/home/marcwoodyard/Jagex/launcher/rs2client: error while loading shared libraries: 
libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by maxice8** [comment]
Here is a workaround i devised in the meantime.

Download the libssl1.0.0 from [here](https://packages.ubuntu.com/bionic-updates/libssl1.0.0), it will have `libssl.so.1.0.0` and `libcrypto.so.1.0.0`

extract it to /packages (or whatever directory) and do

```
flatpak --user override --env=LD_LIBRARY_PATH=/packages/usr/lib/x86_64-linux-gnu com.jagex.RuneScape
flatpak --user override --filesystem=/packages com.jagex.RuneScape
```

**Comment by annadane** [comment]
> Here is a workaround i devised in the meantime.
> 
> Download the libssl1.0.0 from [here](https://packages.ubuntu.com/bionic-updates/libssl1.0.0), it will have `libssl.so.1.0.0` and `libcrypto.so.1.0.0`
> 
> extract it to /packages (or whatever directory) and do
> 
> ```
> flatpak --user override --env=LD_LIBRARY_PATH=/packages/usr/lib/x86_64-linux-gnu com.jagex.RuneScape
> flatpak --user override --filesystem=/packages com.jagex.RuneScape
> ```

Cool. What to do when this gets fixed? Do I need to manually intervene in any way?

**Comment by maxice8** [comment]
Yes, `flatpak --user override --reset com.jagex.Runescape`

**Comment by 1-byte-man** [comment]
What's the equivalent for /packages in fedora.

**Comment by annadane** [comment]
> What's the equivalent for /packages in fedora.

It was just an example. You can make the directory where you like and just replace /packages in the instructions with the directory you made

**Comment by annadane** [comment]
btw, I notice after following the instructions, and then reverting it, the game will still run, I wonder why that is

**Comment by maxice8** [comment]
> What's the equivalent for /packages in fedora.

It doesn't matter, you can extract the libssl1.0.0 from Ubuntu anywhere, you just have to change the --filesystem=$PLACE and --env=LD_LIBRARY_PATH=$place in the commands to the place you extracted them.

**Comment by baconicsynergy** [comment]
You people are so smart! Thank you! I was able to fix the problem on Fedora 32 by following @annadane 's instructions and resetting them. Curious bug

**Comment by marcthe12** [comment]
Note: If you extract inside the ~/.var/app/com.jagex.RuneScape/Jagex folder there is no need to put filesystem permissions.
I could fix it on app level but I am not exactly sure how deal with openssl build system on flatpak due its unusual nature (configure script is ./Configure).

**Comment by Garbee** [comment]
I finally got through all the digging and figured things out. This was introduced when the platform was updated but for some reason wasn't immediately caught (perhaps we were building against a version that still had OpenSSL 1.0.)

OpenSSL 1.0 [was remove in the platform](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/381) container. So to fix this, we will need to move back to 18.08 which includes openssl 1.0 still. Jagex will need to fix the game launcher in order to support newer versions of OpenSSL before we can upgrade (unless someone can figure out how to properly build it internally to a flatpak.)

I'll look into this when possible. Right now, the builder command is messing up on me (issue already open and I'm commenting on that so it is known it is affecting things here) so I can't even get it built due to a missing manifest (that we don't even use or deal with.) Until I'm able to build and test, please use the work-arounds presented here to get things going. Once building is possible again, I'll swing back to this and try to get something stable figured out.

**Comment by marcthe12** [comment]
>  finally got through all the digging and figured things out. This was introduced when the platform was updated but for some reason wasn't immediately caught (perhaps we were building against a version that still had OpenSSL 1.0.)
Its a bug in Jagex build system. They are suppose to build against openssl 1.0, A Jmod commented that on aur the previous time this occured when I was trying get in work on 19.08. It was fixed a couple week later. Looks like someone screwed the buildsystem again.

**Comment by Raatty** [comment]
its times like this i wish the java client still existed for rs3

**Comment by Garbee** [comment]
@marcthe12 That comment really doesn't help clear anything up.

> They are suppose to build against openssl 1.0

Well, 1.0 is what is missing since only 1.1 is in the container. So the problem is in our dependencies of the container. Unless what the comment meant to say is 1.1. Where is the source for that quote you're adding?

**Comment by marcthe12** [comment]
JagexDark commented on:
https://aur.archlinux.org/packages/runescape-launcher/
Here is the quote (unable to link individual comments)

> Looks like there is indeed a mistake there, it should have been linked against libssl 1.1 instead of 1.0 (as per the dependency list), this will be resolved

This was last year on the 2.25 update. 

@Garbee yes I was refering to openssl 1.1 only. Openssl 3.0 is coming soon and it may this worse.

**Comment by Garbee** [comment]
(You can link to specific comments by just clicking on the date of the comment. It is the link with the date timestamp.)

A [later comment](https://aur.archlinux.org/packages/runescape-launcher/?O=20&PP=10#comment-718032) as well shows with 2.2.6 they did indeed upgrade to OpenSSL 1.1. So this is *absolutely* a Jagex build issue. As such, I'm not going to spend time putting a temporary hack in.

Anyone hitting this (which should be everyone) needs to reach out to Jagex and let them know it is broken and you expect a fix.

**Comment by marcthe12** [comment]
I am curious if mod dark has a github account.

**Comment by hevanaa** [comment]
Absolutely insane. 

Previous binaries:

$ ldd runescape  | grep ssl
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007fd7f47e0000)

$ ldd runescape  | grep crypto
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f3eefad6000)

Latest binary:

$ ldd runescape | grep ssl
	libssl.so.1.0.0 => not found

$ ldd runescape | grep ssl
	libssl.so.1.0.0 => not found

Do they even test their own software???

**Comment by Raatty** [comment]
ijagex tests it on an old version of ubuntu i think that does have the correct library

**Comment by hevanaa** [comment]
I just now noticed they have a long time ago (before 2.26?) dropped dynamical dependency on old curl and libGLEW versions. So these are either statically compiled into the binary or dropped completely, as I can't find any trace of them from the ELF file. 

IMHO, it is just bad design to depend on old versions and no better to compile them statically so you can keep those ancient versions. In the case of curl and SSL, it really could make you vulnerable to attacks. These are just basic things that every Linux distribution on the planet mostly does it right (or at least have planned and designed for). 

And how hard could it be to provide a proper repository (it is mostly a file structure on your web server), provide at least a package changelog and bump the version number every time you build. Providing an update with the same version number is just plain..., I don't know... you just don't do that! It's kind of like trying to sneak out bug fixes to your customers, so they don't notice the fatal thing you did in last update. If I had done that deliberately I would be out of work now. 

Sorry, not really on topic as it is an upstream bug, but had to vent somewhere.

**Comment by KeironO** [comment]
Is there absolutely no means of bundling libssl into the flatpak's run time.

**Comment by Garbee** [comment]
"no means", well it is in there now it's just the newest version only. Yes we *could* do it. However, this is clearly a broken package from Jagex. Why should we go fixing their messes all the time? If this is affecting you (as it should all the flatpak users and in fact all users even in Ubuntu direct) reach out to Jagex and let them know so they can address it sooner.

Why should I spend (at least) 5-8 hours hoping to securely patch in a legacy version of SSL when it isn't a problem that should exist in the first place? Then to just remove it once they do fix it.  Solvable problem, yes. Is it worth the investment into compared to other things going on? Absolutely not considering it is a direct bug from the upstream client. And it is directly dealing with the authentication of network requests... I'd rather not go to legacy security things.

It's just a few tokens stacking up on the "Not our problem" and "Security" columns compared to the one token of making it "just work" for users. However, I'd rather not make it just work when doing that involves opening possible security issues with the network.

As I've said before in this thread, go to Jagex's support and let them know this broken package they've shipped affects you and you'd like a fix. That's the only thing that will speed up a fix here. Bundling an older version of SSL is not my idea of a good fix given the situation.

**Comment by peterHoburg** [comment]
It looks like this mornings update fixed this @Garbee ! It looks like Jagex finally got it together (a little...)

**Comment by romulasry** [comment]
@annadane Fixed for you?

**Comment by Garbee** [comment]
This should have been fixed a while ago by Jagex. Closing the issue on out now.
