### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by mrmanitech** [flathub/com.jagex.RuneScape#167]
Error: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb
error: Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.9_amd64.deb

**Comment by ralphocdol** [comment]
![Screenshot_20210626_191557](https://user-images.githubusercontent.com/31056871/123511278-f1b7ca80-d66f-11eb-83fb-08b7046dbdf6.png)

Same here, anyone knows how to deal with this?

**Comment by AsciiWolf** [comment]
#166

**Comment by gasinvein** [comment]
@ralphocdol This is not norm, but the flatpak app maintainers can't do much about it. Upstream shouldn't be publishing updates without bumping .deb release.

**Comment by Garbee** [comment]
Merged in #166 to address this instance. It is very routine that this happens. I'm going to look into the auto-merge stuff and why it isn't working from the bot soon (if I can't get a clear answer tonight on why.)
