### ISSUE TITLE
Font is messed up

### ISSUE THREAD

**Issue by cybbro** [flathub/com.jagex.RuneScape#180]
Hi, I am having font issues on Runescape, font is very hard to read blurry, lacks clarity. 

I am using Ubuntu 21.10 and I don't have font issues anywhere else on a system.

![font settings](https://user-images.githubusercontent.com/10908092/144113264-1869b547-231b-4f24-8a12-059027b3e6e9.png)

![Blurry font](https://user-images.githubusercontent.com/10908092/144113302-a67c2c79-4ebb-44f9-a5bd-18c33e268d8e.png)

GPU Nvidia, Driver 495.44
![GPU](https://user-images.githubusercontent.com/10908092/144113917-d941dcb9-1599-47b8-a6fc-1438d277ef07.png)

Help would be greatly appreciated!

**Comment by Garbee** [comment]
The game does not use any system fonts or system rendering. It is all done in the game itself. They are bitmaps.

Not sure if anything can be done at all here. Have you tested with a non-contained game install to see if the font issue happens there as well? Gut feeling, this is just how the game is and nothing can be done. Certainly not anything from the container side. It's all internal to the game rendering and you'd need to contact Jagex about this.

**Comment by cybbro** [comment]
Understood, thank you
