### ISSUE TITLE
libsframe needs to be copied when updating to runtime 23.08

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.jagex.RuneScape#217]
Hi, this is a heads up.

`ar` since binutils >=2.40 links against libsframe but binutils is entirely in the SDK and not in platform runtime. So `libsframe` needs to be copied, else the `apply_extra` script won't work.

```
cp -a /usr/lib/$(gcc --print-multiarch)/libsframe.so* ${FLATPAK_DEST}/lib
```

Another option is to use bsdtar instead of ar.

Thanks.

**Comment by Garbee** [comment]
Jagex is killing the Linux support slowly. I wonder if it is even worth updating the flatkpak internals a lot given the launcher/jagex account situation.

Seems like this just needs to go into life support mode until Jagex is done with Linux completely.

**Comment by Limero** [comment]
Fixed by https://github.com/flathub/com.jagex.RuneScape/pull/237
