### ISSUE TITLE
Size incorrect: install fails on Linux Mint due to Debian package size mismatch. 

### ISSUE THREAD

**Issue by fusion809** [flathub/com.jagex.RuneScape#22]
Hi,

On Linux Mint 19 Tara (beta) I get this error:

![screenshot from 2018-06-05 13-38-35](https://user-images.githubusercontent.com/4717341/40953996-cf27189c-68c5-11e8-9dd4-efb06f65e7aa.png)

Would be delightful if it could be fixed.

Thanks for your time,
Brenton

**Comment by Garbee** [comment]
PR #21 should have addressed this instance of it being out of date.

**Comment by fusion809** [comment]
Well I detected it 6 hours after it was merged, surely it doesn't take that long to rebuild this package.

**Comment by Garbee** [comment]
Can you run this script and provide the output please?

<details>
<summary>update-debian-check.sh</summary>

```bash
#!/usr/bin/env bash

if ! which curl > /dev/null; then
  echo "Curl is required to check for an updated build."
  exit 1
fi

outputLocation="/tmp/rs.deb"

curl -sL -o $outputLocation "https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb"

echo "The current file size is: $(wc -c < $outputLocation)"
echo "The current sha256sum is: $(sha256sum $outputLocation | cut -d " " -f 1)"

rm $outputLocation
```

</details>

My output shows we have the right checksum and file size in our json to verify the download. So it looks like the actual download during install is incorrect for some reason. I'll look into how to debug it at runtime later today.

<details>
<summary>Output</summary>

```
The current file size is: 3018084
The current sha256sum is: 5ca2a1b5cef8b8c54c05140e183109b57bccd3fb03e660b571c2cb9cfc2b6a28
```

</details>

**Comment by ernestask** [comment]
I get identical checksum and size when manually downloading, so I’m going to guess that the flatpak hasn’t been rebuilt.

**Comment by fusion809** [comment]
Yep I also get:

```bash
The current file size is: 3018084
The current sha256sum is: 5ca2a1b5cef8b8c54c05140e183109b57bccd3fb03e660b571c2cb9cfc2b6a28
```

**Comment by ernestask** [comment]
After hacking in some debug output to see what size Flatpak is expecting:
```
(flatpak install:30291): flatpak-DEBUG: 16:52:17.809: downloaded: 3018084, expected: 3016464
```

3016464 is consistent with the old value: https://github.com/flathub/com.jagex.RuneScape/commit/ecbc367e16650800ebf4ca86fbf66f4593c91da1

**Comment by Garbee** [comment]
Ah `flatpak remote-info flathub com.jagex.RuneScape` provides the info on what is in the repo. I filed an issue on the front-end to try and surface this info on the web page as well.

It is still sitting at Commit f1d0e3ef668c3290ed9705cdc81a7a53fc497a32 which seems to be the last pushed copy. It smells to me like the build process is off-by-one on new pushes. Or that updates have become glacially slow.

<details>
<summary>Output of remote-info</summary>

```
Ref: app/com.jagex.RuneScape/x86_64/stable
ID: com.jagex.RuneScape
Arch: x86_64
Branch: stable
Date: 2018-05-31 21:12:03 +0000
Subject: Update to latest client (f1d0e3ef)
Commit: 8d7f30931ed05b3c27474215909a1e7393543ab603bf9ec36c36bbd4eacfd376
Parent: 688dd4dfa8df4e7acadd123859b5023b310879a01b22edced16a04bf126e533b
Download size: 800.1 kB
Installed size: 2.1 MB
Runtime: org.gnome.Platform/x86_64/3.28
```

</details>

**Comment by Garbee** [comment]
So, merged a commit adding a new script and the system is rebuilt on that now. Install works fine here. Closing this on out, please follow-up here if this isn't the case for ya'll.

Thank you for your patience!
