### ISSUE TITLE
Cannot run - error loading configuration from the website 7,77

### ISSUE THREAD

**Issue by Setayo** [flathub/com.jagex.RuneScape#238]
when running the programme by clicking the icon it appears with a pop up

"There was an error loading the game configuration from the website.
If you have a firewall, check that this program is allowed to access the Internet. (7,77)"

when running from terminal the following errors appear
#Gtk-Message: 15:24:50.067: Failed to load module "atk-bridge"
#Gtk-Message: 15:24:50.079: Failed to load module "canberra-gtk-module"

The game was running perfectly fine some time ago and with absolutely zero changes to system and network I can no longer connect to Runescape via the flatpak specifically, it still runs via Android and soon will be testing if it can run via Steam.

ZorinOS 17 (based on Ubuntu 22.04) using RTX2080

**Comment by Setayo** [comment]
Verified that it does run on Steam, not an ideal solution due to the dependency on running Steam before running Runescape, but it will tide me over

**Comment by absolutez3** [comment]
I have been getting the same error for around the same time. Bolt worked for a bit but now I am getting that (7,77) error there as well. Works on Android. Fedora 39 and RHEL 9 both no go for me.

**Comment by Adamcake** [comment]
I suspect strongly that this is the same issue as https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1781. To fix this for now, you'd need to revert 1363db0cfb30dee2671c62c76551849531d7b1d9.

**Comment by schoentoon** [comment]
You're absolutely correct. After reverting that one commit and rebuilding locally it works again for me.

**Comment by absolutez3** [comment]
@Adamcake I can confirm Bolt is working now thank you!

**Comment by igivefw** [comment]
> You're absolutely correct. After reverting that one commit and rebuilding locally it works again for me.

How did you do this?

**Comment by Limero** [comment]
The bug in the Freedesktop runtime has been resolved, so just do a flatpak update and RuneScape should load correctly. I can't replicate the issue anymore with the latest version of the runtime.

Knowing now it would take them so long to fix it, we should've probably reverted to the old deprecated runtime in the meantime.
