### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by WolfpackN64** [flathub/com.jagex.RuneScape#42]
On Fedora 28 I get "Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher_2.2.4_amd64.deb" when I try to install the Runescape Flatpak through GNOME Software.

**Comment by Garbee** [comment]
Merged #41 to fix this instance.

Apparently I need to look into configuring a text message or push notification of some kind when those get made...

Thanks for the ping.
