### ISSUE TITLE
Music sounds distorted - Fedora 28

### ISSUE THREAD

**Issue by WolfpackN64** [flathub/com.jagex.RuneScape#45]
On Fedora 28 on both my laptop and my desktop, the music sounds distorted. This occurs on both the launcher, the menu and in the game. Strangely enough, the sound effects and everything is totally fine, only the music is distorted (like there's a delay).

**Comment by Garbee** [comment]
Check #6 for the probable solution and see if it works.

**Comment by WolfpackN64** [comment]
Setting the latency to 120ms fixed the problem. Thanks.
