### ISSUE TITLE
Crashes on start up, due to libGL issues

### ISSUE THREAD

**Issue by fusion809** [flathub/com.jagex.RuneScape#49]
Hi,

Before today's update this game launched fine, but now I see the splash screen for a couple of seconds, then it crashes, this is what I see at the command-line:

```bash
/app/extra/runescape: /lib/libcurl.so.4: no version information available (required by /app/extra/runescape)
Gtk-Message: 22:08:58.541: Failed to load module "unity-gtk-module"
/home/fusion809/Jagex/launcher/rs2client: /lib/libcurl.so.4: no version information available (required by /home/fusion809/Jagex/launcher/rs2client)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

`strace -o strace.log flatpak run com.jagex.RuneScape` gives this strace.log: [strace.log.zip](https://github.com/flathub/com.jagex.RuneScape/files/2604139/strace.log.zip). `LD_DEBUG=libs flatpak run com.jagex.RuneScape &> debug.log` gives this debug.log: [debug.log.zip](https://github.com/flathub/com.jagex.RuneScape/files/2604137/debug.log.zip).

Thanks for your time,
Brenton

**Comment by Garbee** [comment]
Yes, Jagex introducing regressions that crash things. However there is nothing we can do in the flatpak to fix that. Typically in 2-3 updates from Jagex these issues just seem to fix themselves on the systems where it appears. The systems affected will also rotate between releases.

**Comment by TingPing** [comment]
If you use Nvidia the updated version is building now: https://flathub.org/builds/#/builders/2/builds/6267

Just `flatpak update` once its done.

**Comment by fusion809** [comment]
@TingPing thank you very much (I use NVIDIA GeForce 1050Ti). Thought I'd have to wait a matter of weeks to have this fixed.

**Comment by fusion809** [comment]
Aha it is fixed!
