### ISSUE TITLE
Fedora 27 audio issues

### ISSUE THREAD

**Issue by JimmyByte** [flathub/com.jagex.RuneScape#6]
I'm experiencing very broken audio on up to date fedora 27, I'm running 64 bit, with latest updates and I noticed that music was muted the first time I launched runescape, and I noticed shortly after that this might have been because sound is heavily broken. The game runs fine on Windows, yet it runs graphically quite well here with Fedora but struggles in the audio.

I'm running fedora on amd processor and an amd graphics card, if that helps.

**Comment by Limero** [comment]
You are right, the audio is messed up. I've only played with the audio muted so I never noticed. I tested running the game outside of Flatpak and it's the same problem, so this is most likely something that has to be fixed by Jagex.

**Comment by jmfgdev** [comment]
Could you try to flatpak the unix-runescape-client?
Sound may be working, and it may be significantly more compatible with more distros than the stock .Deb version that is only meant to run on Ubuntu Lts probably

**Comment by jmfgdev** [comment]
source at https://github.com/hikariknight/rsu-client/ @limero

**Comment by Limero** [comment]
I will not create a Flatpak of an unofficial Java client just to get audio working, but you or anyone else are free to. You can run the binary from a .deb package on any distro and it's the same stuff that's downloaded at runtime with this Flatpak, so audio is most likely broken for anyone using the official client, even on Ubuntu.

**Comment by jmfgdev** [comment]
Could it be possible that this is working on xorg? I have Wayland but could anyone contribute whether they experience this sound problem on other GNU/linuses that don't have wayland? Also does anyone experience it working fine and what GNU/linux distro you're using?

**Comment by Limero** [comment]
I'm using Xorg on Arch Linux with i3wm, but it does not matter as it's not a graphics related issue.

**Comment by Garbee** [comment]
Is this still an ongoing issue?

I don't run Fedora myself (on ChromiumOS as it is right now) but if needed I can get an install running to do some debugging on.

Thank you.

**Comment by Garbee** [comment]
No, Ubuntu from the deb (as long as you install libglew1.10) everything works fine.

The issue seems to be the way Jagex handled the audio when they built the package so specifically to one old version of Ubuntu and aren't caring to maintain it properly. I don't think there is too much that can be done here, except have everyone experiencing the issue open up support tickets with Jagex about it. Maybe if they see enough users having problems they'll finally put a developer into fixing the Linux stuff.

**Comment by Limero** [comment]
If it works on Ubuntu, then if anyone is able to figure out what dependency is causing it, we could bundle that ancient dependency in our flatpak.

**Comment by Garbee** [comment]
<details>
<summary>Dependencies</summary>

```
 Depends: libsdl2-2.0-0 (>= 2.0.2+dfsg1-3ubuntu1.1), libglew1.10 (>= 1.10.0-3), libc6 (>= 2.19-0ubuntu6.6), libcurl3-gnutls (>= 7.35.0-1ubuntu2.5), libstdc++6 (>= 4.8.4-2ubuntu1~14.04), libgcc1 (>= 1:4.9.1-0ubuntu1), libvorbisenc2 (>= 1.3.2-1.3ubuntu1), libwebkitgtk-1.0-0 (>= 2.4.8-1ubuntu1~ubuntu14.04.1)
```

</details>

The only dependency that is audio related that I'm seeing is [libvorbisenc2](https://packages.debian.org/sid/libvorbisenc2). So, that might be worth a shot bundling a compile of into the flatpak with.

**Comment by AsciiWolf** [comment]
@Garbee I have tried [to bundle](https://pastebin.com/k3L2HbXX) libvorbis, unfortunately nothing changed - audio is still broken.

**Comment by Garbee** [comment]
<details>
<summary>Bundle libvorbisenc2 diff</summary>

```
diff --git a/com.jagex.RuneScape.json b/com.jagex.RuneScape.json
index faa7870..5dd239c 100644
--- a/com.jagex.RuneScape.json
+++ b/com.jagex.RuneScape.json
@@ -99,6 +99,20 @@
                 }
             ]
         },
+        {
+            "name": "libvorbis",
+            "cleanup": [
+                "/include",
+                "/lib/pkgconfig"
+            ],
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.gz",
+                    "sha256": "6ed40e0241089a42c48604dc00e362beee00036af2d8b3f46338031c9e0351cb"
+                }
+            ]
+        },
         {
             "name": "runescape",
             "buildsystem": "simple",
```

</details>

FYI you can use the `details` element and put patches right into comments cleanly. Or just use a gist from github. No need to link to ad-ridden sites like pastebin to host simple code snippets like that.

<details>
<summary>Inline markup for code in comments</summary>

```
<details>
<summary>Some short description</summary>

<!-- Ensure an empty newline  and do the triple ticks for code in markdown -->
<!-- Insert code -->
<!-- Triple ticks for ending code snippet in markdown, then ensure extra newline before closing details-->

</details>
````

</details>

Now, on the note of it not working for the issue at hand, that's a bummer. However, I still think it would be a good idea to include as many of the dependencies as we can internally. Just to help make sure the flatpak can run in as many environments as possible in case of other inconsistencies.

**Comment by KeironO** [comment]
The following dependencies are required for the official NXT launcher:

- libsdl2-2.0-0 (>= 2.0.2+dfsg1-3ubuntu1.1)
- ibglew1.10 (>= 1.10.0-3)
- libc6 (>= 2.19-0ubuntu6.6)
- libcurl3-gnutls (>= 7.35.0-1ubuntu2.5)
- libstdc++6 (>= 4.8.4-2ubuntu1~14.04)
- libgcc1 (>= 1:4.9.1-0ubuntu1)
- libvorbisenc2 (>= 1.3.2-1.3ubuntu1)
- libwebkitgtk-1.0-0 (>= 2.4.8-1ubuntu1~ubuntu14.04.1)

From my own experiences , I've seen audio issues with ```libwebkitgtk``` before they released 3.0.0. Not sure how far we can really resolve this issue, seeing as Jagex seem fairly happy letting the game client rot on Linux.

**Comment by Limero** [comment]
Maintainer of the Arch Linux package has implemented a fix for audio from a thread on the official forums. It should be possible to do the same with the Flatpak. http://services.runescape.com/m=forum/forums.ws?409,410,815,65955068,goto,1

https://aur.archlinux.org/cgit/aur.git/commit/?h=runescape-launcher&id=792efda07cf88eaa0dd9cdae4060aeda0f4f5f56

https://aur.archlinux.org/cgit/aur.git/commit/?h=runescape-launcher&id=7c1b5b9995ef21ddb5a88fa3061cc50cb967490e

**Comment by AsciiWolf** [comment]
@Limero You're right, setting the PulseAudio latency manually fixed the issue! (Although it had to be set to 120ms, not 60ms.) I will make a PR for this fix.

**Comment by Garbee** [comment]
Just merged the fix from @AsciiWolf in for this. If the 80ms latency still crackles for your machines, then you can run the flatpak like so and set your own time to find one that works:

`flatpak run --env=PULSE_LATENCY_MSEC=120 com.jagex.RuneScape`

Just change the `120` in the command with your timing.

**Comment by dandelionred** [comment]
Please consider adding the PULSE_LATENCY_MSEC stuff into github.com/flathub/com.jagex.RuneScape/README.md!! I've just got crackling sound on a fresh ubuntu 18.04 install so it should be a common problem but info on it is hidden in issues.  
  
Btw in my case 120ms wasn't enough. 200ms works well.

**Comment by DanRuckz** [comment]
I found that on arch installing pipewire-common-pulse-git from the AUR helped, maybe you can find the equivalent in fedora. ofc, that will install pipewire. If you already have pipewire installed not from this package, then this package will replace the one on the system.
