### ISSUE TITLE
Strict image size requirements preventing new builds from going out

### ISSUE THREAD

**Issue by Garbee** [flathub/com.jagex.RuneScape#76]
Ref: https://flathub.org/builds/#/builders/8/builds/407

Updates to flathub now strict check image sizes. We are referencing Jagex's images directly so they are too large. So either we make our own screenshots or we take and resize theirs to self-host.

**Comment by TingPing** [comment]
This should be fixed soon but a temporary work around would be: https://github.com/flathub/org.freedesktop.fwupd/blob/33e9ea94dad243a7dff9a72111e8eb7e69f64333/flathub.json

**Comment by Garbee** [comment]
Sweet, just updated that. So hopefully the next build will pop right out shortly.

Thank kyou @TingPing. It would have been a while before I figured that out, or asked.

**Comment by hfiguiere** [comment]
Hasn't this been fixed ?
