### ISSUE TITLE
Extra data wrong side

### ISSUE THREAD

**Issue by JhohnC** [flathub/com.jagex.RuneScape#84]
I got this error when trying to install the flatpack.
Failed to install com.jagex.RuneScape: Wrong size for extra data https://content.runescape.com/downloads/ubuntu/pool/non-free/r/runescape-launcher/runescape-launcher_2.2.4_amd64.deb

**Comment by JhohnC** [comment]
Sorry I saw the pull request now

**Comment by Garbee** [comment]
This will be fixed once the new build deploys in hopefully a few minutes.
